### ISSUE TITLE
0.4.3 Update - Not able to login (Failed with Invalid Input Parameters.)

### ISSUE THREAD

**Issue by intronix** [5paisa/py5paisa#140]
latest version of python and 5paisa api 0.4.3 was used.....

It was working untill now, after the update, it is not working
i am not able login

the credentials that I had provided or entered are totally correct and I had cross checked it twice, it was working for 2 months, now it is not working anymore

from py5paisa import FivePaisaClient
cred={
"APP_NAME":"YOUR APP_NAME",
"APP_SOURCE":"YOUR APP_SOURCE",
"USER_ID":"YOUR USER_ID",
"PASSWORD":"YOUR PASSWORD",
"USER_KEY":"YOUR USERKEY",
"ENCRYPTION_KEY":"YOUR ENCRYPTION_KEY"
}

client = FivePaisaClient(email="[random_email@xyz.com](mailto:random_email@xyz.com)", passwd="password", dob="YYYYMMDD",cred=cred)
client.login()

error message
22:18:47 | Invalid Input Parameters.

**Comment by manmay-nakhashi** [comment]
facing same issue

**Comment by intronix** [comment]
@5paisa Kindly look into this issue, My algo's stopped working, i am not able to place order. Thanks for your understanding

**Comment by kairon007** [comment]
@5paisa +1

**Comment by manmay-nakhashi** [comment]
@5paisa  any update on this ?

**Comment by addypy** [comment]
Figured out a quick fix for this by monkey patching the code.

Navigate to the package directory, to this file ***py5paisa/py5paisa/urlconst.py*** 

Change the `V4` to `V3` 

So, replace this -
```py
LOGIN_ROUTE = f'{BaseUrl}V4/LoginRequestMobileNewbyEmail'
```
with this -
```py
LOGIN_ROUTE = f'{BaseUrl}V3/LoginRequestMobileNewbyEmail'
```

**Comment by kairon007** [comment]
@addypy Still not working for me

**Comment by addypy** [comment]
@kairon007 

Uninstall the package with pip. Clone the repository to your local system and make these changes.

Use os.chdir(PACKAGE_DIR) or sys.path.append(PACKAGE_DIR) where PACKAGE_DIR is the full path to the cloned repository in your system.

It should work.

**Comment by Sksingh97** [comment]
> Figured out a quick fix for this by patching the source code.
> 
> Navigate to the package directory, to this file _**py5paisa/py5paisa/urlconst.py**_
> 
> Change the `V4` to `V3`
> 
> So, replace this -
> 
> ```python
> LOGIN_ROUTE = f'{BaseUrl}V4/LoginRequestMobileNewbyEmail'
> ```
> 
> with this -
> 
> ```python
> LOGIN_ROUTE = f'{BaseUrl}V3/LoginRequestMobileNewbyEmail'
> ```
> 
> You may also have to comment out the `self.Jwt_token=resp["body"]["JWTToken"]` line in _**py5paisa/py5paisa/py5paisa.py**_
> 
> ```python
>     def _login_request(self, route):
>         try:
>             requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
>             res = self.session.post(route, json=self.login_payload, headers=HEADERS)
>             resp=res.json()
>             print(resp)
> #            self.Jwt_token=resp["body"]["JWTToken"]
>             return res.json()
>         except Exception as e:
>             log_response(e)
> ```

Thanks Worked for me

**Comment by kairon007** [comment]
@addypy @Sksingh97 Me too getting Invalid JWT. What's wrong with 5paisa team? @5paisa

**Comment by 5paisa** [comment]
Hi all,

All these login issues have been fixed!

**Comment by kairon007** [comment]
@5paisa Getting name 'SOCKET_DEPTH_PAYLOAD' is not defined before Invalid Input Parameters now

**Comment by Sksingh97** [comment]
@5paisa getting same error name 'SOCKET_DEPTH_PAYLOAD' is not defined.

**Comment by intronix** [comment]
08:32:32 | name 'SOCKET_DEPTH_PAYLOAD' is not defined

**Comment by 5paisa** [comment]
This is fixed in v0.4.7

**Comment by kairon007** [comment]
@5paisa Updated to 0.4.7 , now the " Invalid Input Parameters." is back. Please handle this asap. A lot of time is being wasted. Thanks

**Comment by 5paisa** [comment]
Please help us with your app source?

**Comment by Sksingh97** [comment]
@5paisa I am just creating the fiveP client and simply calling login with the creds and facing same problem as @kairon007 

Sample code: 
self.client = FivePaisaClient(email="**********", passwd="************", dob="********", cred=cred)
self.client.login()

Getting error:
 18:25:41 | Invalid Input Parameters.
 
 Can you please let us know if there is any changes i have to do in order to make it work.

**Comment by 5paisa** [comment]
Whoever is facing invalid input parameters, please put down the app source you are using in the cred dictionary.
Will have to check for all facing this error.

**Comment by kairon007** [comment]
Is there someway i can dm you my cred instead of posting it publicly? Thanks

**Comment by intronix** [comment]
@5paisa  Instead asking everyone's App source, it is better to post the example code which is working from your side. 
In my case everthing was working 2 weeks before perfectly, after the update now nothing is working. I higly doubt that existing App source is causing this problem . So  i recommend to post working example or update the wiki we will follow if there is any change . Thanks

**Comment by 5paisa** [comment]
Please mail the same to support@5paisa.com.
App source will be necessary for evaluating the same.

**Comment by 5paisa** [comment]
Till then, request all facing login issue to use OAuth approach.

Read here:- https://github.com/5paisa/py5paisa#oauth

**Comment by kairon007** [comment]
@5paisa I've emailed the credentials on the email. For Oauth, please let us know where we can find the vendor keys?

**Comment by 5paisa** [comment]
Go to tradestation.5paisa.com -> Menu Options.
![keys](https://user-images.githubusercontent.com/65898074/159111117-fd005086-fd20-4387-866b-d4a4ca12732c.png)

**Comment by kairon007** [comment]
@5paisa There's no vendor key here?
![FireShot Capture 002 - 5paisa - tradestation 5paisa com](https://user-images.githubusercontent.com/488036/159111450-94b411e2-d0d3-4b78-bf07-b39299b45ebd.png)

**Comment by intronix** [comment]
@5paisa  : I tired use user key as vendor key and for redirecting url i used locahost, but response is as follows 
to be frank OAUTH method usage documentation is not user friendly, better provide us simple code snippet for the usage of atleast . it would be helpful. 
Error : 
Server Error in '/WebVendorLogin' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

Requested URL: /WebVendorLogin/VLogin/localhost

**Comment by intronix** [comment]
I have sent my App source to the support mail, kindly revert back after your analysis.

**Comment by 5paisa** [comment]
Please don't put your credentials on any public platform.
@intronix , will share a example for implementing the same.

**Comment by kairon007** [comment]
> I have sent my App source to the support mail, kindly revert back after your analysis.

Me too. Please revert asap

**Comment by 5paisa** [comment]
Hi all,

Sorry for the inconvenience caused.

All issues related to login have been fixed.

Please relogin to tradestation and update your existing API keys (Encryption key) to continue using!

**Comment by kairon007** [comment]
@5paisa Seriously? I updated to 0.4.8, updated the api keys( Encryption key) since it was the only one changed and still the same old "Invalid input parameters"

**Comment by intronix** [comment]
@5paisa Nothing changed with the update of version and Encryption key. Same error again :) "Invalid input parameters"

**Comment by 5paisa** [comment]
Have you updated your cred dictionary with new Key provided?

Please send another mail to support@5paisa.com after checking that

**Comment by intronix** [comment]
After two weeks of time, finally i am able to login now.  @5paisa thanks for the support

**Comment by kairon007** [comment]
Same here, working now. Thanks
